import React, { useState } from 'react';
import { Clock, Copy, Download, Check, ShieldCheck, Sliders, FileCode, Sparkles, Code2, Mail } from 'lucide-react';

export default function CronScheduler() {
  const [cronExpr, setCronExpr] = useState('0 0 * * *');
  const [customCron, setCustomCron] = useState('');
  const [branch, setBranch] = useState('main');
  const [userEmail, setUserEmail] = useState(() => localStorage.getItem('gh_email') || 'your-github-email@gmail.com');
  const [realismMode, setRealismMode] = useState('realistic'); // 'realistic', 'consistent', 'heavy', 'fixed'
  const [contentType, setContentType] = useState('leetcode'); // 'leetcode', 'journal', 'log', 'hybrid'
  const [minCommits, setMinCommits] = useState(1);
  const [maxCommits, setMaxCommits] = useState(4);
  const [skipChance, setSkipChance] = useState(15); // % chance to skip (rest day)
  const [commitMsg, setCommitMsg] = useState('feat(solution): daily LeetCode algorithm solution');
  const [activeFileTab, setActiveFileTab] = useState('yaml'); // 'yaml' | 'script'

  const [copiedYaml, setCopiedYaml] = useState(false);
  const [copiedScript, setCopiedScript] = useState(false);

  const activeCron = cronExpr === 'custom' ? customCron || '0 0 * * *' : cronExpr;

  const handleRealismChange = (mode) => {
    setRealismMode(mode);
    if (mode === 'realistic') {
      setMinCommits(1);
      setMaxCommits(4);
      setSkipChance(15);
    } else if (mode === 'consistent') {
      setMinCommits(2);
      setMaxCommits(5);
      setSkipChance(0);
    } else if (mode === 'heavy') {
      setMinCommits(5);
      setMaxCommits(10);
      setSkipChance(0);
    } else if (mode === 'fixed') {
      setMinCommits(1);
      setMaxCommits(1);
      setSkipChance(0);
    }
  };

  const handleContentTypeChange = (type) => {
    setContentType(type);
    if (type === 'leetcode') {
      setCommitMsg('feat(solution): daily LeetCode algorithm solution');
    } else if (type === 'journal') {
      setCommitMsg('docs(journal): daily technical study notes');
    } else if (type === 'log') {
      setCommitMsg('chore(auto-commit): daily activity sync');
    } else if (type === 'hybrid') {
      setCommitMsg('feat(sync): daily activity & study update');
    }
  };

  const generateWorkflowYaml = () => {
    return `name: Auto Commit Cron Scheduler

on:
  schedule:
    - cron: '${activeCron}'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Execute Auto-Commit Script
        env:
          COMMIT_MODE: '${realismMode}'
          CONTENT_TYPE: '${contentType}'
          MIN_COMMITS: '${minCommits}'
          MAX_COMMITS: '${maxCommits}'
          SKIP_CHANCE: '${(skipChance / 100).toFixed(2)}'
        run: node scripts/auto_commit.js

      - name: Commit & Push Changes
        env:
          USER_EMAIL: \${{ secrets.COMMIT_EMAIL || '${userEmail}' }}
          USER_NAME: \${{ github.actor }}
        run: |
          git config --global user.name "\${USER_NAME}"
          git config --global user.email "\${USER_EMAIL}"
          git add solutions/ notes/ data/ 2>/dev/null || true
          git diff --quiet && git diff --staged --quiet || git commit -m "${commitMsg}"
          git push origin ${branch}
`;
  };

  const generateScriptJs = () => {
    return `/**
 * GitHub Actions Cron Execution Script
 * Auto-generated by GitGraph Studio
 * Supports LeetCode Solutions, Dev Notes, Activity Logs, and Hybrid mode
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MODE = process.env.COMMIT_MODE || '${realismMode}';
const MIN_COMMITS = parseInt(process.env.MIN_COMMITS || '${minCommits}', 10);
const MAX_COMMITS = parseInt(process.env.MAX_COMMITS || '${maxCommits}', 10);
const SKIP_CHANCE = parseFloat(process.env.SKIP_CHANCE || '${(skipChance / 100).toFixed(2)}');
const CONTENT_TYPE = process.env.CONTENT_TYPE || '${contentType}';

const LEETCODE_PROBLEMS = [
  { id: '0001', name: 'two_sum', lang: 'js', title: 'Two Sum', diff: 'Easy', code: \`// LeetCode 0001: Two Sum\\nfunction twoSum(nums, target) {\\n  const map = new Map();\\n  for (let i = 0; i < nums.length; i++) {\\n    const diff = target - nums[i];\\n    if (map.has(diff)) return [map.get(diff), i];\\n    map.set(nums[i], i);\\n  }\\n  return [];\\n}\` },
  { id: '0002', name: 'add_two_numbers', lang: 'py', title: 'Add Two Numbers', diff: 'Medium', code: \`# LeetCode 0002: Add Two Numbers\\ndef addTwoNumbers(l1, l2):\\n    dummy = ListNode(0)\\n    curr, carry = dummy, 0\\n    while l1 or l2 or carry:\\n        val = (l1.val if l1 else 0) + (l2.val if l2 else 0) + carry\\n        carry = val // 10\\n        curr.next = ListNode(val % 10)\\n        curr = curr.next\\n        l1 = l1.next if l1 else None\\n        l2 = l2.next if l2 else None\\n    return dummy.next\` },
  { id: '0020', name: 'valid_parentheses', lang: 'js', title: 'Valid Parentheses', diff: 'Easy', code: \`// LeetCode 0020: Valid Parentheses\\nfunction isValid(s) {\\n  const stack = [];\\n  const pairs = { ')': '(', '}': '{', ']': '[' };\\n  for (const char of s) {\\n    if (!pairs[char]) stack.push(char);\\n    else if (stack.pop() !== pairs[char]) return false;\\n  }\\n  return stack.length === 0;\\n}\` },
  { id: '0070', name: 'climbing_stairs', lang: 'js', title: 'Climbing Stairs', diff: 'Easy', code: \`// LeetCode 0070: Climbing Stairs\\nfunction climbStairs(n) {\\n  if (n <= 2) return n;\\n  let first = 1, second = 2;\\n  for (let i = 3; i <= n; i++) {\\n    const third = first + second;\\n    first = second;\\n    second = third;\\n  }\\n  return second;\\n}\` },
  { id: '0121', name: 'best_time_to_buy_and_sell_stock', lang: 'py', title: 'Best Time to Buy & Sell Stock', diff: 'Easy', code: \`# LeetCode 0121: Best Time to Buy & Sell Stock\\ndef maxProfit(prices):\\n    min_price, max_profit = float('inf'), 0\\n    for price in prices:\\n        min_price = min(min_price, price)\\n        max_profit = max(max_profit, price - min_price)\\n    return max_profit\` }
];

const JOURNAL_TOPICS = [
  "System Architecture: Microservices vs Monolith Tradeoffs",
  "React 19 Server Components and Suspense Deep Dive",
  "Optimizing PostgreSQL Indexing and B-Trees",
  "Redis Caching Strategies: Cache-Aside vs Write-Through",
  "Docker Containerization & Multi-Stage Builds"
];

function generateContent(type, index, timestamp) {
  if (type === 'hybrid') {
    const choices = ['leetcode', 'journal', 'log'];
    type = choices[Math.floor(Math.random() * choices.length)];
  }

  if (type === 'leetcode') {
    const problem = LEETCODE_PROBLEMS[Math.floor(Math.random() * LEETCODE_PROBLEMS.length)];
    const solutionsDir = path.join(__dirname, '../solutions');
    if (!fs.existsSync(solutionsDir)) fs.mkdirSync(solutionsDir, { recursive: true });

    const filename = \`\${problem.id}_\${problem.name}.\${problem.lang}\`;
    const filePath = path.join(solutionsDir, filename);
    const content = \`/**\\n * Problem: \${problem.title} (\${problem.diff})\\n * Last Updated: \${timestamp}\\n */\\n\\n\${problem.code}\\n\\n// Solution run #\${index + 1}\\n\`;

    fs.writeFileSync(filePath, content);
    console.log(\`📝 Generated LeetCode Solution: solutions/\${filename}\`);
  } else if (type === 'journal') {
    const topic = JOURNAL_TOPICS[Math.floor(Math.random() * JOURNAL_TOPICS.length)];
    const notesDir = path.join(__dirname, '../notes');
    if (!fs.existsSync(notesDir)) fs.mkdirSync(notesDir, { recursive: true });

    const dateStr = timestamp.split('T')[0];
    const filename = \`\${dateStr}_note_\${index + 1}.md\`;
    const filePath = path.join(notesDir, filename);
    const content = \`# Technical Learning Log — \${dateStr}\\n\\n## Topic: \${topic}\\n\\n- **Timestamp**: \${timestamp}\\n- **Status**: Completed Daily Study\\n\`;

    fs.writeFileSync(filePath, content);
    console.log(\`📖 Generated Dev Note: notes/\${filename}\`);
  } else {
    const logFile = path.join(__dirname, '../data/activity_log.txt');
    const dataDir = path.dirname(logFile);
    if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

    const logEntry = \`[CRON RUN \${timestamp} #\${index + 1}] — "Consistency is key."\\n\`;
    fs.appendFileSync(logFile, logEntry);
    console.log(\`✅ Appended to activity log: data/activity_log.txt\`);
  }
}

function runScheduledCommit() {
  if (MODE === 'realistic' && Math.random() < SKIP_CHANCE) {
    console.log("🎲 Realistic human skip triggered today (rest day). No commits generated.");
    return;
  }

  const commitCount = Math.floor(Math.random() * (MAX_COMMITS - MIN_COMMITS + 1)) + MIN_COMMITS;
  const now = new Date().toISOString();

  for (let i = 0; i < commitCount; i++) {
    generateContent(CONTENT_TYPE, i, now);
  }

  console.log(\`🎉 Finished executing \${commitCount} automated commits for type: \${CONTENT_TYPE}\`);
}

runScheduledCommit();
`;
  };

  const yamlContent = generateWorkflowYaml();
  const scriptContent = generateScriptJs();

  const handleCopy = () => {
    const content = activeFileTab === 'yaml' ? yamlContent : scriptContent;
    navigator.clipboard.writeText(content);
    if (activeFileTab === 'yaml') {
      setCopiedYaml(true);
      setTimeout(() => setCopiedYaml(false), 2000);
    } else {
      setCopiedScript(true);
      setTimeout(() => setCopiedScript(false), 2000);
    }
  };

  const handleDownload = () => {
    const content = activeFileTab === 'yaml' ? yamlContent : scriptContent;
    const filename = activeFileTab === 'yaml' ? 'auto_commit.yml' : 'auto_commit.js';
    const mimeType = activeFileTab === 'yaml' ? 'text/yaml' : 'text/javascript';

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="panel-card">
      <div className="panel-title">
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Clock size={20} style={{ color: 'var(--gh-level-4)' }} />
          <span>Automated Cron Scheduler & Generator</span>
        </div>
        <span className="badge">
          <ShieldCheck size={12} style={{ display: 'inline', marginRight: '4px' }} />
          Serverless GitHub Actions
        </span>
      </div>

      <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1.25rem' }}>
        Configure how often, how realistically, and <strong>what type of real files</strong> (LeetCode solutions, Dev Notes, Logs) your bot commits.
      </p>

      {/* Grid Controls Section */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1.25rem', marginBottom: '1.25rem' }}>
        
        {/* Schedule Frequency */}
        <div className="form-group" style={{ margin: 0 }}>
          <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <Clock size={14} style={{ color: 'var(--gh-level-4)' }} /> Schedule Frequency
          </label>
          <select
            className="form-input"
            value={cronExpr}
            onChange={(e) => setCronExpr(e.target.value)}
          >
            <option value="0 0 * * *">Every Day at Midnight UTC (0 0 * * *) [Default]</option>
            <option value="0 9,17 * * *">Twice Daily (9 AM & 5 PM UTC)</option>
            <option value="0 12 * * 1-5">Weekdays Only (Mon-Fri at Noon UTC)</option>
            <option value="0 12 * * 1,3,5">3x Weekly (Mon, Wed, Fri)</option>
            <option value="0 0,12 * * *">Twice Daily (Every 12 Hours)</option>
            <option value="0 */6 * * *">Every 6 Hours (Heavy Streak)</option>
            <option value="custom">⚙️ Custom Cron Expression...</option>
          </select>

          {cronExpr === 'custom' && (
            <input
              type="text"
              className="form-input"
              style={{ marginTop: '0.5rem' }}
              placeholder="e.g. 0 8 * * 1-5"
              value={customCron}
              onChange={(e) => setCustomCron(e.target.value)}
            />
          )}
        </div>

        {/* What to Commit (Content Type) */}
        <div className="form-group" style={{ margin: 0 }}>
          <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <Code2 size={14} style={{ color: 'var(--gh-level-4)' }} /> What to Commit (File Content)
          </label>
          <select
            className="form-input"
            value={contentType}
            onChange={(e) => handleContentTypeChange(e.target.value)}
          >
            <option value="leetcode">🧩 LeetCode / DSA Solutions (solutions/XXXX_problem.js)</option>
            <option value="journal">📝 Technical Study Notes (notes/YYYY-MM-DD-note.md)</option>
            <option value="log">⚡ Activity Logs & Quotes (data/activity_log.txt)</option>
            <option value="hybrid">🔀 Hybrid Mix (Random LeetCode + Notes + Logs)</option>
          </select>
        </div>

        {/* Primary GitHub Email for Profile Credit */}
        <div className="form-group" style={{ margin: 0 }}>
          <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <Mail size={14} style={{ color: 'var(--gh-level-4)' }} /> GitHub Email (For Graph Credit)
          </label>
          <input
            type="email"
            className="form-input"
            value={userEmail}
            onChange={(e) => {
              setUserEmail(e.target.value);
              localStorage.setItem('gh_email', e.target.value);
            }}
            placeholder="your-github-email@gmail.com"
          />
        </div>

        {/* Target Branch */}
        <div className="form-group" style={{ margin: 0 }}>
          <label className="form-label">Target Branch</label>
          <input
            type="text"
            className="form-input"
            value={branch}
            onChange={(e) => setBranch(e.target.value)}
            placeholder="main"
          />
        </div>
      </div>

      {/* Advanced Fine-Tuning Controls */}
      <div style={{ background: 'rgba(3, 7, 18, 0.6)', border: '1px solid var(--border-color)', borderRadius: '8px', padding: '0.85rem', marginBottom: '1.25rem' }}>
        <div style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--gh-level-4)', marginBottom: '0.6rem', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
          <Sliders size={14} /> Realism Fine-Tuning & Variable Parameters
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '0.85rem' }}>
          <div>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Commit Realism Mode:</span>
            <select
              className="form-input"
              style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem', marginTop: '4px' }}
              value={realismMode}
              onChange={(e) => handleRealismChange(e.target.value)}
            >
              <option value="realistic">🌱 Realistic (1-4 commits + rest days)</option>
              <option value="consistent">🔥 Consistent (2-5 commits daily)</option>
              <option value="heavy">🚀 Heavy (5-10 commits daily)</option>
              <option value="fixed">🎯 Fixed 1 Commit Per Trigger</option>
            </select>
          </div>
          <div>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Min Commits / Run:</span>
            <input
              type="number"
              min="1"
              max="20"
              className="form-input"
              style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem', marginTop: '4px' }}
              value={minCommits}
              onChange={(e) => setMinCommits(parseInt(e.target.value, 10) || 1)}
            />
          </div>
          <div>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Max Commits / Run:</span>
            <input
              type="number"
              min="1"
              max="30"
              className="form-input"
              style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem', marginTop: '4px' }}
              value={maxCommits}
              onChange={(e) => setMaxCommits(parseInt(e.target.value, 10) || 4)}
            />
          </div>
          <div>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Human Rest Day Chance:</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '4px' }}>
              <input
                type="number"
                min="0"
                max="50"
                className="form-input"
                style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem' }}
                value={skipChance}
                onChange={(e) => setSkipChance(parseInt(e.target.value, 10) || 0)}
              />
              <span style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>%</span>
            </div>
          </div>
          <div style={{ gridColumn: 'span 2' }}>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Commit Message Format:</span>
            <input
              type="text"
              className="form-input"
              style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem', marginTop: '4px' }}
              value={commitMsg}
              onChange={(e) => setCommitMsg(e.target.value)}
            />
          </div>
        </div>
      </div>

      {/* File Tab Selector & Code Viewer */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
        <div style={{ display: 'flex', gap: '0.4rem' }}>
          <button
            className={`btn ${activeFileTab === 'yaml' ? 'btn-primary' : 'btn-outline'}`}
            style={{ padding: '0.3rem 0.65rem', fontSize: '0.75rem' }}
            onClick={() => setActiveFileTab('yaml')}
          >
            <FileCode size={13} /> .github/workflows/auto_commit.yml
          </button>
          <button
            className={`btn ${activeFileTab === 'script' ? 'btn-primary' : 'btn-outline'}`}
            style={{ padding: '0.3rem 0.65rem', fontSize: '0.75rem' }}
            onClick={() => setActiveFileTab('script')}
          >
            <FileCode size={13} /> scripts/auto_commit.js
          </button>
        </div>

        <div style={{ display: 'flex', gap: '0.4rem' }}>
          <button className="btn btn-secondary" style={{ padding: '0.3rem 0.65rem', fontSize: '0.75rem' }} onClick={handleCopy}>
            {((activeFileTab === 'yaml' && copiedYaml) || (activeFileTab === 'script' && copiedScript)) ? (
              <Check size={13} style={{ color: 'var(--gh-level-4)' }} />
            ) : (
              <Copy size={13} />
            )}
            {((activeFileTab === 'yaml' && copiedYaml) || (activeFileTab === 'script' && copiedScript)) ? 'Copied!' : 'Copy File'}
          </button>
          <button className="btn btn-primary" style={{ padding: '0.3rem 0.65rem', fontSize: '0.75rem' }} onClick={handleDownload}>
            <Download size={13} /> Download {activeFileTab === 'yaml' ? 'auto_commit.yml' : 'auto_commit.js'}
          </button>
        </div>
      </div>

      {/* Code Box Display */}
      <div className="code-box" style={{ maxHeight: '280px', overflowY: 'auto' }}>
        <pre>{activeFileTab === 'yaml' ? yamlContent : scriptContent}</pre>
      </div>

      <div style={{ marginTop: '1rem', fontSize: '0.8rem', color: 'var(--text-dim)', background: '#010409', padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
        📁 <strong>Setup Instruction:</strong> Copy <code style={{ color: 'var(--gh-level-4)' }}>.github/workflows/auto_commit.yml</code> and <code style={{ color: 'var(--gh-level-4)' }}>scripts/auto_commit.js</code> into any new repository to activate this automated cron bot!
      </div>
    </div>
  );
}
