import React, { useState } from 'react';
import { Clock, Copy, Download, Check, ShieldCheck, Zap, Sliders, FileCode, Sparkles } from 'lucide-react';

export default function CronScheduler() {
  const [cronExpr, setCronExpr] = useState('0 0 * * *');
  const [customCron, setCustomCron] = useState('');
  const [branch, setBranch] = useState('main');
  const [realismMode, setRealismMode] = useState('realistic'); // 'realistic', 'consistent', 'heavy', 'fixed'
  const [minCommits, setMinCommits] = useState(1);
  const [maxCommits, setMaxCommits] = useState(4);
  const [skipChance, setSkipChance] = useState(15); // % chance to skip (rest day)
  const [commitMsg, setCommitMsg] = useState('chore(auto-commit): daily activity sync');
  const [activeFileTab, setActiveFileTab] = useState('yaml'); // 'yaml' | 'script'

  const [copiedYaml, setCopiedYaml] = useState(false);
  const [copiedScript, setCopiedScript] = useState(false);

  const activeCron = cronExpr === 'custom' ? customCron || '0 0 * * *' : cronExpr;

  const handleRealismChange = (mode) => {
    setRealismMode(mode);
    if (mode === 'realistic') {
      setMinCommits(1);
      setMaxCommits(4);
      setSkipChance(15);
    } else if (mode === 'consistent') {
      setMinCommits(2);
      setMaxCommits(5);
      setSkipChance(0);
    } else if (mode === 'heavy') {
      setMinCommits(5);
      setMaxCommits(10);
      setSkipChance(0);
    } else if (mode === 'fixed') {
      setMinCommits(1);
      setMaxCommits(1);
      setSkipChance(0);
    }
  };

  const generateWorkflowYaml = () => {
    return `name: Auto Commit Cron Scheduler

on:
  schedule:
    - cron: '${activeCron}'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Execute Auto-Commit Script
        env:
          COMMIT_MODE: '${realismMode}'
          MIN_COMMITS: '${minCommits}'
          MAX_COMMITS: '${maxCommits}'
          SKIP_CHANCE: '${(skipChance / 100).toFixed(2)}'
        run: node scripts/auto_commit.js

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/activity_log.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "${commitMsg}"
          git push origin ${branch}
`;
  };

  const generateScriptJs = () => {
    return `/**
 * GitHub Actions Cron Execution Script
 * Auto-generated by GitGraph Studio
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LOG_FILE = path.join(__dirname, '../data/activity_log.txt');

const MODE = process.env.COMMIT_MODE || '${realismMode}';
const MIN_COMMITS = parseInt(process.env.MIN_COMMITS || '${minCommits}', 10);
const MAX_COMMITS = parseInt(process.env.MAX_COMMITS || '${maxCommits}', 10);
const SKIP_CHANCE = parseFloat(process.env.SKIP_CHANCE || '${(skipChance / 100).toFixed(2)}');

const MOTIVATIONAL_QUOTES = [
  "Consistency is the code of success.",
  "Small daily improvements over time lead to stunning results.",
  "Automate the routine, unleash the creative.",
  "Building the future, one commit at a time.",
  "Keep shipping, stay inspired.",
  "Code, commit, repeat.",
  "Progress over perfection."
];

function runScheduledCommit() {
  if (MODE === 'realistic' && Math.random() < SKIP_CHANCE) {
    console.log("🎲 Realistic human skip triggered today (rest day). No commits generated.");
    return;
  }

  const dataDir = path.dirname(LOG_FILE);
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }

  const commitCount = Math.floor(Math.random() * (MAX_COMMITS - MIN_COMMITS + 1)) + MIN_COMMITS;
  const now = new Date();

  for (let i = 0; i < commitCount; i++) {
    const timestamp = now.toISOString();
    const randomQuote = MOTIVATIONAL_QUOTES[Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length)];
    const logContent = "[CRON RUN " + timestamp + " #" + (i + 1) + "/" + commitCount + "] — \\"" + randomQuote + "\\"\\n";
    fs.appendFileSync(LOG_FILE, logContent);
  }

  console.log("✅ Activity log updated with " + commitCount + " commits at " + now.toISOString());
}

runScheduledCommit();
`;
  };

  const yamlContent = generateWorkflowYaml();
  const scriptContent = generateScriptJs();

  const handleCopy = () => {
    const content = activeFileTab === 'yaml' ? yamlContent : scriptContent;
    navigator.clipboard.writeText(content);
    if (activeFileTab === 'yaml') {
      setCopiedYaml(true);
      setTimeout(() => setCopiedYaml(false), 2000);
    } else {
      setCopiedScript(true);
      setTimeout(() => setCopiedScript(false), 2000);
    }
  };

  const handleDownload = () => {
    const content = activeFileTab === 'yaml' ? yamlContent : scriptContent;
    const filename = activeFileTab === 'yaml' ? 'auto_commit.yml' : 'auto_commit.js';
    const mimeType = activeFileTab === 'yaml' ? 'text/yaml' : 'text/javascript';

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="panel-card">
      <div className="panel-title">
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Clock size={20} style={{ color: 'var(--gh-level-4)' }} />
          <span>Automated Cron Scheduler & Generator</span>
        </div>
        <span className="badge">
          <ShieldCheck size={12} style={{ display: 'inline', marginRight: '4px' }} />
          Serverless GitHub Actions
        </span>
      </div>

      <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1.25rem' }}>
        Configure how often and how realistically your automated contribution bot commits to GitHub.
      </p>

      {/* Grid Controls Section */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1.25rem', marginBottom: '1.25rem' }}>
        
        {/* Schedule Frequency */}
        <div className="form-group" style={{ margin: 0 }}>
          <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <Clock size={14} style={{ color: 'var(--gh-level-4)' }} /> Schedule Frequency
          </label>
          <select
            className="form-input"
            value={cronExpr}
            onChange={(e) => setCronExpr(e.target.value)}
          >
            <option value="0 0 * * *">Every Day at Midnight UTC (0 0 * * *) [Default]</option>
            <option value="0 9,17 * * *">Twice Daily (9 AM & 5 PM UTC)</option>
            <option value="0 12 * * 1-5">Weekdays Only (Mon-Fri at Noon UTC)</option>
            <option value="0 12 * * 1,3,5">3x Weekly (Mon, Wed, Fri)</option>
            <option value="0 0,12 * * *">Twice Daily (Every 12 Hours)</option>
            <option value="0 */6 * * *">Every 6 Hours (Heavy Streak)</option>
            <option value="custom">⚙️ Custom Cron Expression...</option>
          </select>

          {cronExpr === 'custom' && (
            <input
              type="text"
              className="form-input"
              style={{ marginTop: '0.5rem' }}
              placeholder="e.g. 0 8 * * 1-5"
              value={customCron}
              onChange={(e) => setCustomCron(e.target.value)}
            />
          )}
        </div>

        {/* Realism & Intensity Mode */}
        <div className="form-group" style={{ margin: 0 }}>
          <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <Sparkles size={14} style={{ color: 'var(--gh-level-4)' }} /> Commit Realism & Intensity
          </label>
          <select
            className="form-input"
            value={realismMode}
            onChange={(e) => handleRealismChange(e.target.value)}
          >
            <option value="realistic">🌱 Realistic Human Developer (1-4 commits/day + random rest days)</option>
            <option value="consistent">🔥 Consistent Contributor (2-5 commits every day)</option>
            <option value="heavy">🚀 Heavy Streak Builder (5-10 commits every day)</option>
            <option value="fixed">🎯 Fixed 1 Commit Per Trigger</option>
          </select>
        </div>

        {/* Target Branch */}
        <div className="form-group" style={{ margin: 0 }}>
          <label className="form-label">Target Branch</label>
          <input
            type="text"
            className="form-input"
            value={branch}
            onChange={(e) => setBranch(e.target.value)}
            placeholder="main"
          />
        </div>

        {/* Commit Message Prefix */}
        <div className="form-group" style={{ margin: 0 }}>
          <label className="form-label">Commit Message Prefix</label>
          <input
            type="text"
            className="form-input"
            value={commitMsg}
            onChange={(e) => setCommitMsg(e.target.value)}
            placeholder="chore(auto-commit): daily activity sync"
          />
        </div>
      </div>

      {/* Advanced Fine-Tuning Controls */}
      <div style={{ background: 'rgba(3, 7, 18, 0.6)', border: '1px solid var(--border-color)', borderRadius: '8px', padding: '0.85rem', marginBottom: '1.25rem' }}>
        <div style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--gh-level-4)', marginBottom: '0.6rem', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
          <Sliders size={14} /> Realism Fine-Tuning & Variable Parameters
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '0.85rem' }}>
          <div>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Min Commits / Run:</span>
            <input
              type="number"
              min="1"
              max="20"
              className="form-input"
              style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem', marginTop: '4px' }}
              value={minCommits}
              onChange={(e) => setMinCommits(parseInt(e.target.value, 10) || 1)}
            />
          </div>
          <div>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Max Commits / Run:</span>
            <input
              type="number"
              min="1"
              max="30"
              className="form-input"
              style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem', marginTop: '4px' }}
              value={maxCommits}
              onChange={(e) => setMaxCommits(parseInt(e.target.value, 10) || 4)}
            />
          </div>
          <div>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Human Rest Day Chance:</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '4px' }}>
              <input
                type="number"
                min="0"
                max="50"
                className="form-input"
                style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem' }}
                value={skipChance}
                onChange={(e) => setSkipChance(parseInt(e.target.value, 10) || 0)}
              />
              <span style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>%</span>
            </div>
          </div>
        </div>
      </div>

      {/* File Tab Selector & Code Viewer */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
        <div style={{ display: 'flex', gap: '0.4rem' }}>
          <button
            className={`btn ${activeFileTab === 'yaml' ? 'btn-primary' : 'btn-outline'}`}
            style={{ padding: '0.3rem 0.65rem', fontSize: '0.75rem' }}
            onClick={() => setActiveFileTab('yaml')}
          >
            <FileCode size={13} /> .github/workflows/auto_commit.yml
          </button>
          <button
            className={`btn ${activeFileTab === 'script' ? 'btn-primary' : 'btn-outline'}`}
            style={{ padding: '0.3rem 0.65rem', fontSize: '0.75rem' }}
            onClick={() => setActiveFileTab('script')}
          >
            <FileCode size={13} /> scripts/auto_commit.js
          </button>
        </div>

        <div style={{ display: 'flex', gap: '0.4rem' }}>
          <button className="btn btn-secondary" style={{ padding: '0.3rem 0.65rem', fontSize: '0.75rem' }} onClick={handleCopy}>
            {((activeFileTab === 'yaml' && copiedYaml) || (activeFileTab === 'script' && copiedScript)) ? (
              <Check size={13} style={{ color: 'var(--gh-level-4)' }} />
            ) : (
              <Copy size={13} />
            )}
            {((activeFileTab === 'yaml' && copiedYaml) || (activeFileTab === 'script' && copiedScript)) ? 'Copied!' : 'Copy File'}
          </button>
          <button className="btn btn-primary" style={{ padding: '0.3rem 0.65rem', fontSize: '0.75rem' }} onClick={handleDownload}>
            <Download size={13} /> Download {activeFileTab === 'yaml' ? 'auto_commit.yml' : 'auto_commit.js'}
          </button>
        </div>
      </div>

      {/* Code Box Display */}
      <div className="code-box" style={{ maxHeight: '280px', overflowY: 'auto' }}>
        <pre>{activeFileTab === 'yaml' ? yamlContent : scriptContent}</pre>
      </div>

      <div style={{ marginTop: '1rem', fontSize: '0.8rem', color: 'var(--text-dim)', background: '#010409', padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
        📁 <strong>Setup Instruction:</strong> Commit <code style={{ color: 'var(--gh-level-4)' }}>.github/workflows/auto_commit.yml</code> and <code style={{ color: 'var(--gh-level-4)' }}>scripts/auto_commit.js</code> to your GitHub repository to activate this custom cron schedule!
      </div>
    </div>
  );
}
