/**
 * GitHub Actions Cron Execution Script
 * Auto-generated by GitGraph Studio
 * Supports LeetCode Solutions, Dev Notes, Activity Logs, and Hybrid mode
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MODE = process.env.COMMIT_MODE || 'realistic';
const MIN_COMMITS = parseInt(process.env.MIN_COMMITS || '1', 10);
const MAX_COMMITS = parseInt(process.env.MAX_COMMITS || '4', 10);
const SKIP_CHANCE = parseFloat(process.env.SKIP_CHANCE || '0.15');
const CONTENT_TYPE = process.env.CONTENT_TYPE || 'leetcode'; // 'leetcode', 'journal', 'log', 'hybrid'

// Real LeetCode & DSA Problem Pool
const LEETCODE_PROBLEMS = [
  { id: '0001', name: 'two_sum', lang: 'js', title: 'Two Sum', diff: 'Easy', code: `// LeetCode 0001: Two Sum\n// Time: O(N), Space: O(N)\nfunction twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const diff = target - nums[i];\n    if (map.has(diff)) return [map.get(diff), i];\n    map.set(nums[i], i);\n  }\n  return [];\n}` },
  { id: '0002', name: 'add_two_numbers', lang: 'py', title: 'Add Two Numbers', diff: 'Medium', code: `# LeetCode 0002: Add Two Numbers\n# Time: O(N), Space: O(N)\nclass ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef addTwoNumbers(l1, l2):\n    dummy = ListNode(0)\n    curr, carry = dummy, 0\n    while l1 or l2 or carry:\n        val = (l1.val if l1 else 0) + (l2.val if l2 else 0) + carry\n        carry = val // 10\n        curr.next = ListNode(val % 10)\n        curr = curr.next\n        l1 = l1.next if l1 else None\n        l2 = l2.next if l2 else None\n    return dummy.next` },
  { id: '0003', name: 'longest_substring_without_repeating', lang: 'ts', title: 'Longest Substring Without Repeating Characters', diff: 'Medium', code: `// LeetCode 0003: Longest Substring Without Repeating Characters\nfunction lengthOfLongestSubstring(s: string): number {\n  let left = 0, maxLen = 0;\n  const seen = new Set<string>();\n  for (let right = 0; right < s.length; right++) {\n    while (seen.has(s[right])) {\n      seen.delete(s[left]);\n      left++;\n    }\n    seen.add(s[right]);\n    maxLen = Math.max(maxLen, right - left + 1);\n  }\n  return maxLen;\n}` },
  { id: '0015', name: '3sum', lang: 'py', title: '3Sum', diff: 'Medium', code: `# LeetCode 0015: 3Sum\ndef threeSum(nums):\n    nums.sort()\n    res = []\n    for i in range(len(nums)-2):\n        if i > 0 and nums[i] == nums[i-1]: continue\n        l, r = i+1, len(nums)-1\n        while l < r:\n            s = nums[i] + nums[l] + nums[r]\n            if s < 0: l += 1\n            elif s > 0: r -= 1\n            else:\n                res.append([nums[i], nums[l], nums[r]])\n                while l < r and nums[l] == nums[l+1]: l += 1\n                while l < r and nums[r] == nums[r-1]: r -= 1\n                l += 1; r -= 1\n    return res` },
  { id: '0020', name: 'valid_parentheses', lang: 'js', title: 'Valid Parentheses', diff: 'Easy', code: `// LeetCode 0020: Valid Parentheses\nfunction isValid(s) {\n  const stack = [];\n  const pairs = { ')': '(', '}': '{', ']': '[' };\n  for (const char of s) {\n    if (!pairs[char]) stack.push(char);\n    else if (stack.pop() !== pairs[char]) return false;\n  }\n  return stack.length === 0;\n}` },
  { id: '0053', name: 'maximum_subarray', lang: 'cpp', title: 'Maximum Subarray (Kadane Algo)', diff: 'Medium', code: `// LeetCode 0053: Maximum Subarray\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint maxSubArray(vector<int>& nums) {\n    int maxSoFar = nums[0], currMax = nums[0];\n    for (size_t i = 1; i < nums.size(); ++i) {\n        currMax = max(nums[i], currMax + nums[i]);\n        maxSoFar = max(maxSoFar, currMax);\n    }\n    return maxSoFar;\n}` },
  { id: '0070', name: 'climbing_stairs', lang: 'js', title: 'Climbing Stairs (DP)', diff: 'Easy', code: `// LeetCode 0070: Climbing Stairs\nfunction climbStairs(n) {\n  if (n <= 2) return n;\n  let first = 1, second = 2;\n  for (let i = 3; i <= n; i++) {\n    const third = first + second;\n    first = second;\n    second = third;\n  }\n  return second;\n}` },
  { id: '0121', name: 'best_time_to_buy_and_sell_stock', lang: 'py', title: 'Best Time to Buy and Sell Stock', diff: 'Easy', code: `# LeetCode 0121: Best Time to Buy & Sell Stock\ndef maxProfit(prices):\n    min_price, max_profit = float('inf'), 0\n    for price in prices:\n        min_price = min(min_price, price)\n        max_profit = max(max_profit, price - min_price)\n    return max_profit` },
  { id: '0200', name: 'number_of_islands', lang: 'js', title: 'Number of Islands (BFS/DFS)', diff: 'Medium', code: `// LeetCode 0200: Number of Islands\nfunction numIslands(grid) {\n  let count = 0;\n  for (let r = 0; r < grid.length; r++) {\n    for (let c = 0; c < grid[0].length; c++) {\n      if (grid[r][c] === '1') {\n        count++;\n        dfs(grid, r, c);\n      }\n    }\n  }\n  return count;\n}\nfunction dfs(g, r, c) {\n  if (r<0||c<0||r>=g.length||c>=g[0].length||g[r][c]==='0') return;\n  g[r][c] = '0';\n  dfs(g,r+1,c); dfs(g,r-1,c); dfs(g,r,c+1); dfs(g,r,c-1);\n}` },
  { id: '0206', name: 'reverse_linked_list', lang: 'py', title: 'Reverse Linked List', diff: 'Easy', code: `# LeetCode 0206: Reverse Linked List\ndef reverseList(head):\n    prev, curr = None, head\n    while curr:\n        nxt = curr.next\n        curr.next = prev\n        prev = curr\n        curr = nxt\n    return prev` }
];

// Technical Journal Topic Pool
const JOURNAL_TOPICS = [
  "System Architecture: Microservices vs Monolith Tradeoffs",
  "React 19 Server Components and Suspense Deep Dive",
  "Optimizing PostgreSQL Indexing and B-Trees",
  "Redis Caching Strategies: Cache-Aside vs Write-Through",
  "Docker Containerization & Multi-Stage Builds",
  "Kubernetes Pod Lifecycle & Horizontal Auto-Scaling",
  "TypeScript Generics & Advanced Conditional Types",
  "Graph Algorithms: Dijkstra vs A* Shortest Path"
];

function generateContent(type, index, timestamp) {
  if (type === 'hybrid') {
    const choices = ['leetcode', 'journal', 'log'];
    type = choices[Math.floor(Math.random() * choices.length)];
  }

  if (type === 'leetcode') {
    const problem = LEETCODE_PROBLEMS[Math.floor(Math.random() * LEETCODE_PROBLEMS.length)];
    const solutionsDir = path.join(__dirname, '../solutions');
    if (!fs.existsSync(solutionsDir)) fs.mkdirSync(solutionsDir, { recursive: true });

    const filename = `${problem.id}_${problem.name}.${problem.lang}`;
    const filePath = path.join(solutionsDir, filename);
    const content = `/**\n * Problem: ${problem.title} (${problem.diff})\n * Last Updated: ${timestamp}\n */\n\n${problem.code}\n\n// Verified solution run #${index + 1}\n`;

    fs.writeFileSync(filePath, content);
    console.log(`📝 Generated LeetCode Solution: solutions/${filename}`);
  } else if (type === 'journal') {
    const topic = JOURNAL_TOPICS[Math.floor(Math.random() * JOURNAL_TOPICS.length)];
    const notesDir = path.join(__dirname, '../notes');
    if (!fs.existsSync(notesDir)) fs.mkdirSync(notesDir, { recursive: true });

    const dateStr = timestamp.split('T')[0];
    const filename = `${dateStr}_note_${index + 1}.md`;
    const filePath = path.join(notesDir, filename);
    const content = `# Technical Learning Log — ${dateStr}\n\n## Topic: ${topic}\n\n- **Timestamp**: ${timestamp}\n- **Status**: Completed Daily Study\n\n### Key Takeaways:\n1. Understood fundamental trade-offs in distributed systems.\n2. Implemented modular unit test coverage.\n`;

    fs.writeFileSync(filePath, content);
    console.log(`📖 Generated Dev Note: notes/${filename}`);
  } else {
    // Activity Log
    const logFile = path.join(__dirname, '../data/activity_log.txt');
    const dataDir = path.dirname(logFile);
    if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

    const logEntry = `[CRON RUN ${timestamp} #${index + 1}] — "Consistency is key."\n`;
    fs.appendFileSync(logFile, logEntry);
    console.log(`✅ Appended to activity log: data/activity_log.txt`);
  }
}

function runScheduledCommit() {
  if (MODE === 'realistic' && Math.random() < SKIP_CHANCE) {
    console.log("🎲 Realistic human skip triggered today (rest day). No commits generated.");
    return;
  }

  const commitCount = Math.floor(Math.random() * (MAX_COMMITS - MIN_COMMITS + 1)) + MIN_COMMITS;
  const now = new Date().toISOString();

  for (let i = 0; i < commitCount; i++) {
    generateContent(CONTENT_TYPE, i, now);
  }

  console.log(`🎉 Finished executing ${commitCount} automated commits for type: ${CONTENT_TYPE}`);
}

runScheduledCommit();
